<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="1" hostname="P4ALAP-7172YCJ" name="demo.acn.internal.tests.Sample_Test_1" tests="3" failures="1" timestamp="16 Feb 2018 15:23:22 GMT" time="51.552" errors="0">
  <testcase name="LoginTest" time="28.943" classname="demo.acn.internal.tests.Sample_Test_1"/>
  <testcase name="LoginTest" time="21.708" classname="demo.acn.internal.tests.Sample_Test_1">
    <failure type="java.lang.AssertionError" message="Login functionality failing. Expected: Login Success but Actual: Login Failure">
      <![CDATA[java.lang.AssertionError: Login functionality failing. Expected: Login Success but Actual: Login Failure
	at org.testng.Assert.fail(Assert.java:93)
	at demo.acn.internal.utilities.GenericKeywords.reportFailure(GenericKeywords.java:275)
	at demo.acn.internal.utilities.AppKeywords.verifylogin(AppKeywords.java:57)
	at demo.acn.internal.utilities.Keywords.executeKeywords(Keywords.java:58)
	at demo.acn.internal.tests.Sample_Test_1.LoginTest(Sample_Test_1.java:50)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:414)
	at org.testng.internal.thread.ThreadUtil$1.call(ThreadUtil.java:52)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- LoginTest -->
  <testcase name="LoginTest" time="0.901" classname="demo.acn.internal.tests.Sample_Test_1">
    <skipped/>
  </testcase> <!-- LoginTest -->
</testsuite> <!-- demo.acn.internal.tests.Sample_Test_1 -->
